import json

from resource import Source
iris = Source("./data/iris.csv", "csv", json.dumps({"header": True, "delimiter": ","}), {"fields": [{"metadata": {}, "name": "sepallength", "nullable": True, "type": "double"}, {"metadata": {}, "name": "sepalwidth", "nullable": True, "type": "double"}, {"metadata": {}, "name": "petallength", "nullable": True, "type": "double"}, {"metadata": {}, "name": "petalwidth", "nullable": True, "type": "double"}, {"metadata": {"label": True}, "name": "class", "nullable": True, "type": "string"}], "type": "struct"})
sample_libsvm_data = Source("./data/sample_libsvm_data.txt", "libsvm", json.dumps({}), {"fields": [{"metadata": {"label": True}, "name": "label", "nullable": True, "type": "double"}, {"metadata": {"numFeatures": 692}, "name": "features", "nullable": True, "type": {"class": "org.apache.spark.ml.linalg.VectorUDT", "pyClass": "pyspark.ml.linalg.VectorUDT", "sqlType": {"fields": [{"metadata": {}, "name": "type", "nullable": False, "type": "byte"}, {"metadata": {}, "name": "size", "nullable": True, "type": "integer"}, {"metadata": {}, "name": "indices", "nullable": True, "type": {"containsNull": False, "elementType": "integer", "type": "array"}}, {"metadata": {}, "name": "values", "nullable": True, "type": {"containsNull": False, "elementType": "double", "type": "array"}}], "type": "struct"}, "type": "udt"}}], "type": "struct"})
sample_kmeans_data = Source("./data/sample_kmeans_data.txt", "libsvm", json.dumps({"header": True, "delimiter": " "}), {"fields":[{"metadata":{"label": True},"name":"label","nullable":True,"type":"double"},{"metadata":{"numFeatures":3},"name":"features","nullable":True,"type":{"class":"org.apache.spark.ml.linalg.VectorUDT","pyClass":"pyspark.ml.linalg.VectorUDT","sqlType":{"fields":[{"metadata":{},"name":"type","nullable":False,"type":"byte"},{"metadata":{},"name":"size","nullable":True,"type":"integer"},{"metadata":{},"name":"indices","nullable":True,"type":{"containsNull":False,"elementType":"integer","type":"array"}},{"metadata":{},"name":"values","nullable":True,"type":{"containsNull":False,"elementType":"double","type":"array"}}],"type":"struct"},"type":"udt"}}],"type":"struct"})
sample_linear_regression_data = Source("./data/sample_linear_regression_data.txt", "libsvm", json.dumps({"header": True, "delimiter": " "}), {"fields": [{"metadata": {"label": True}, "name": "label", "nullable": True, "type": "double"}, {"metadata": {"numFeatures": 10}, "name": "features", "nullable": True, "type": {"class": "org.apache.spark.ml.linalg.VectorUDT", "pyClass": "pyspark.ml.linalg.VectorUDT", "sqlType": {"fields": [{"metadata": {}, "name": "type", "nullable": False, "type": "byte"}, {"metadata": {}, "name": "size", "nullable": True, "type": "integer"}, {"metadata": {}, "name": "indices", "nullable": True, "type": {"containsNull": False, "elementType": "integer", "type": "array"}}, {"metadata": {}, "name": "values", "nullable": True, "type": {"containsNull": False, "elementType": "double", "type": "array"}}], "type": "struct"}, "type": "udt"}}], "type": "struct"})
sample_multiclass_classification_data = Source("./data/sample_multiclass_classification_data.txt", "libsvm", json.dumps({"header": True, "delimiter": ","}), {"fields": [{"metadata": {"label": True}, "name": "label", "nullable": True, "type": "double"}, {"metadata": {"numFeatures": 4}, "name": "features", "nullable": False, "type": {"class": "org.apache.spark.ml.linalg.VectorUDT", "pyClass": "pyspark.ml.linalg.VectorUDT", "sqlType": {"fields": [{"metadata": {}, "name": "type", "nullable": False, "type": "byte"}, {"metadata": {}, "name": "size", "nullable": True, "type": "integer"}, {"metadata": {}, "name": "indices", "nullable": True, "type": {"containsNull": False, "elementType": "integer", "type": "array"}}, {"metadata": {}, "name": "values", "nullable": True, "type": {"containsNull": False, "elementType": "double", "type": "array"}}], "type": "struct"}, "type": "udt"}}], "type": "struct"})
sample_lda_libsvm_data = Source("./data/sample_lda_libsvm_data.txt", "libsvm", json.dumps({"header": True, "delimiter": ","}), {"fields":[{"metadata":{"label": True},"name":"label","nullable":True,"type":"double"},{"metadata":{"numFeatures":11},"name":"features","nullable":True,"type":{"class":"org.apache.spark.ml.linalg.VectorUDT","pyClass":"pyspark.ml.linalg.VectorUDT","sqlType":{"fields":[{"metadata":{},"name":"type","nullable":False,"type":"byte"},{"metadata":{},"name":"size","nullable":True,"type":"integer"},{"metadata":{},"name":"indices","nullable":True,"type":{"containsNull":False,"elementType":"integer","type":"array"}},{"metadata":{},"name":"values","nullable":True,"type":{"containsNull":False,"elementType":"double","type":"array"}}],"type":"struct"},"type":"udt"}}],"type":"struct"})
sample_movielens_ratings = Source("./data/sample_movielens_ratings.txt", "libsvm", json.dumps({"header": True, "delimiter": ","}), {"fields":[{"metadata":{"label": True},"name":"label","nullable":True,"type":"double"},{"metadata":{"numFeatures":11},"name":"features","nullable":True,"type":{"class":"org.apache.spark.ml.linalg.VectorUDT","pyClass":"pyspark.ml.linalg.VectorUDT","sqlType":{"fields":[{"metadata":{},"name":"type","nullable":False,"type":"byte"},{"metadata":{},"name":"size","nullable":True,"type":"integer"},{"metadata":{},"name":"indices","nullable":True,"type":{"containsNull":False,"elementType":"integer","type":"array"}},{"metadata":{},"name":"values","nullable":True,"type":{"containsNull":False,"elementType":"double","type":"array"}}],"type":"struct"},"type":"udt"}}],"type":"struct"})
test = Source("./data/test.data", "csv", json.dumps({"header": True, "delimiter": ","}), {"fields":[{"metadata":{},"name":"user","nullable":True,"type":"double"},{"metadata":{},"name":"item","nullable":True,"type":"double"},{"metadata":{"label": True},"name":"rating","nullable":True,"type":"double"}],"type":"struct"})
